spring:
  main:
    bannerMode: off
    webApplicationType: none
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

client:
  portfolio:
    filePath: classpath:/config/portfolio.csv